name: Tauri Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Publish Windows Release (32 & 64-bit)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-pc-windows-msvc, x86_64-pc-windows-msvc

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install dependencies
        run: bun install

      # --- Build 64-bit ---
      - name: Build Tauri App - 64-bit
        uses: tauri-apps/tauri-action@v0
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "billsoft v__VERSION__ (64-bit)"
          releaseDraft: false
          prerelease: false
          args: "--target x86_64-pc-windows-msvc"

      - name: Move 64-bit updater files (if exist)
        shell: pwsh
        run: |
          $json = "src-tauri/target/x86_64-pc-windows-msvc/release/bundle/updater/latest.json"
          if (Test-Path $json) {
            New-Item -ItemType Directory -Force -Path artifacts/updater/x64
            Copy-Item "$json" -Destination "artifacts/updater/x64/latest.json"
            Copy-Item "src-tauri/target/x86_64-pc-windows-msvc/release/bundle/updater/*.sig" -Destination "artifacts/updater/x64/"
          } else {
            Write-Host "64-bit updater not found, skipping..."
          }

      # --- Build 32-bit ---
      - name: Build Tauri App - 32-bit
        uses: tauri-apps/tauri-action@v0
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "billsoft v__VERSION__ (32-bit)"
          releaseDraft: false
          prerelease: false
          args: "--target i686-pc-windows-msvc"

      - name: Move 32-bit updater files (if exist)
        shell: pwsh
        run: |
          $json = "src-tauri/target/i686-pc-windows-msvc/release/bundle/updater/latest.json"
          if (Test-Path $json) {
            New-Item -ItemType Directory -Force -Path artifacts/updater/x86
            Copy-Item "$json" -Destination "artifacts/updater/x86/latest.json"
            Copy-Item "src-tauri/target/i686-pc-windows-msvc/release/bundle/updater/*.sig" -Destination "artifacts/updater/x86/"
          } else {
            Write-Host "32-bit updater not found, skipping..."
          }

      - name: Upload Installers and Updater Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
            src-tauri/target/i686-pc-windows-msvc/release/bundle/nsis/*.exe
            src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/*.msi
            artifacts/updater/x64/latest.json
            artifacts/updater/x64/*.sig
            artifacts/updater/x86/latest.json
            artifacts/updater/x86/*.sig
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
